### ISSUE TITLE
无法创建容器

### ISSUE THREAD

**Issue by padoru233** [HoshinoRei/l4d2server_docker#17]
参考文档的方法无法创建容器，使用`docker compose up -d`命令有“Error response from daemon: cannot mount volume over existing file, file exists /var/lib/docker/overlay2/fe7ab4d8ce5a4206624660c917a2d758599953fbf73258d669a63da8d41f8843/merged/home/steam/l4d2server/left4dead2/host.txt”报错

**Comment by HoshinoRei** [comment]
没想到居然有人用。抱歉，小玲忘记更新文档了。 `volumes` 加这么一行就可以了。`host.txt` 文件需要自己创建，内容可以为空。
`- ./host.txt:/home/steam/l4d2server/left4dead2/host.txt:ro`
