### ISSUE TITLE
请问, 小玲的自建服务器现在控制台还能connect上吗?

### ISSUE THREAD

**Issue by yiksun** [HoshinoRei/l4d2server_docker#33]
我这两天试了2种不同的docker方案, 都是connect不上, 游戏端显示max tried 10 times

服务器则是停在了
```
Connection to Steam servers successful.
   VAC secure mode is activated.
```

**Comment by yiksun** [comment]
我找到原因了, 2.2.3.8更新后source mod和meta mod都要重新编译.
纯净服(没有任何插件的)也要关闭"大厅匹配"功能才能connect
server.cfg添加
```
sv_allow_lobby_connect_only 0
sv_force_unreserved 1
```

**Comment by HoshinoRei** [comment]
一般如果显示到这里就可以连接了。

```
Connection to Steam servers successful.
   VAC secure mode is activated.
```

如果不行应该是哪里配置有问题，我自己的话都是 `sv_allow_lobby_connect_only 0` 的，没有连不上的情况。
